In [2]:
import pandas as pd
import numpy as np

In [8]:
path = "Release20_mapdata.csv"

In [9]:
df = pd.read_csv(path)

In [36]:
df

,Media Market,Market State,dma,Total Airings 9Apr20 to 25Oct20,Est. Cost 9Apr20 to 25Oct29,Pro-Biden Airings 9Apr20 to 25Oct20,Pro-Trump Airings 9Apr20 to 25Oct20,Biden Ad Adv 9Apr20 to 25Oct20,Total Airings 12Oct20 to 25Oct20,Est. Cost 12Oct20 to 25Oct20,Pro-Biden Airings 12Oct20 to 25Oct20,Pro-Trump Airings 12Oct20 to 25Oct20,Biden Ad Adv 12Oct20 to 25Oct20
0,ABILENE-SWEETWATER,TX,662,38,5020,13,25,-12,15,"$2,890",13,2,11
1,"ALBANY, GA",GA,525,"6,325",803140,719,"5,606","-4,887","1,691","$269,520",620,"1,071",-451
2,"ALBANY, NY",NY,532,94,4000,85,9,76,94,"$4,000",85,9,76
3,ALBUQUERQUE,NM,790,"1,109",205980,74,"1,035",-961,92,"$12,150",72,20,52
4,ALEXANDRIA,LA,644,12,380,10,2,8,12,$380,10,2,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,WILMINGTON,NC,550,"12,295",2570680,"6,048","6,247",-199,"1,471","$428,250",788,683,105
209,YAKIMA,WA,810,130,5000,27,103,-76,33,$870,27,6,21
210,YOUNGSTOWN,OH,536,"3,124",680170,"3,067",57,"3,010",608,"$149,840",606,2,604
211,YUMA-EL CENTRO,AZ,771,"7,047",1053230,"6,541",506,"6,035","1,774","$184,540","1,766",8,"1,758"
212,ZANESVILLE,OH,596,54,11760,53,1,52,3,$230,2,1,1

In [11]:
df.columns

Index(['Media Market', 'Market State', 'dma',
       'Total Airings 9Apr20 to 25Oct20', 'Est. Cost 9Apr20 to 25Oct29',
       'Pro-Biden Airings 9Apr20 to 25Oct20',
       'Pro-Trump Airings 9Apr20 to 25Oct20', 'Biden Ad Adv 9Apr20 to 25Oct20',
       'Total Airings 12Oct20 to 25Oct20', 'Est. Cost 12Oct20 to 25Oct20',
       'Pro-Biden Airings 12Oct20 to 25Oct20',
       'Pro-Trump Airings 12Oct20 to 25Oct20',
       'Biden Ad Adv 12Oct20 to 25Oct20'],
      dtype='object')

In [47]:
def dollars_to_int(df, name):
    if (df[name].dtype == np.int64):
        return
    df[name]=  df[name].apply(lambda x: "".join(x.lstrip()[1:].split(','))).astype(np.int64)

def number_to_int(df, name):
    if (df[name].dtype == np.int64):
        return
    df[name]=  df[name].apply(lambda x: "".join(x.lstrip().split(','))).astype(np.int64)
    
dollars_to_int(df, 'Est. Cost 9Apr20 to 25Oct29') 
number_to_int(df, "Total Airings 9Apr20 to 25Oct20")
dollars_to_int(df, 'Est. Cost 12Oct20 to 25Oct20')
number_to_int(df, "Total Airings 12Oct20 to 25Oct20")

In [51]:
df['average_cost_per_airing 9Apr20 to 25Oct20'] =  (df['Est. Cost 9Apr20 to 25Oct29'])/ df['Total Airings 9Apr20 to 25Oct20']
df['average_cost_per_airing 12Oct20 to 25Oct20'] = df['Est. Cost 12Oct20 to 25Oct20']/ df['Total Airings 12Oct20 to 25Oct20']

In [54]:
df.describe()

,dma,Total Airings 9Apr20 to 25Oct20,Est. Cost 9Apr20 to 25Oct29,Total Airings 12Oct20 to 25Oct20,Est. Cost 12Oct20 to 25Oct20,average_cost_per_airing 9Apr20 to 25Oct20,average_cost_per_airing 12Oct20 to 25Oct20
count,213.000000,213.000000,2.130000e+02,213.000000,2.130000e+02,213.000000,213.000000
mean,641.446009,5000.784038,3.785591e+06,1006.953052,9.995697e+05,427.529885,458.898169
std,114.377821,10378.061124,1.110584e+07,1972.891061,3.048888e+06,1320.927262,1295.942010
min,-1.000000,3.000000,1.200000e+02,2.000000,1.200000e+02,18.846154,10.714286
25%,552.000000,38.000000,2.570000e+03,20.000000,1.150000e+03,60.555556,53.157895
50%,628.000000,135.000000,1.744000e+04,54.000000,6.020000e+03,143.242344,112.133333
75%,725.000000,3566.000000,1.126350e+06,812.000000,3.393800e+05,418.319245,471.568627
max,999.000000,53911.000000,9.767437e+07,9009.000000,2.574914e+07,17798.589700,17048.198758